using System;
using System.Collections.Generic;

// -----===== autogenerated code =====-----
// ReSharper disable All
// generator: BasicUnitGenerator, DerivedUnitGenerator
// suggestion: File scope namespace is possible, use [AssumeDefinedNamespace]
namespace iSukces.UnitedValues
{
    [Serializable]
    public partial class ForceUnit : IUnit, IEquatable<ForceUnit>
    {
        /// <summary>
        /// creates instance of ForceUnit
        /// </summary>
        /// <param name="unitName">name of unit</param>
        public ForceUnit(string unitName)
        {
            if (unitName is null)
                throw new NullReferenceException(nameof(unitName));
            unitName = unitName.Trim();
            if (unitName.Length == 0)
                throw new ArgumentException(nameof(unitName));
            UnitName = unitName;
        }

        public bool Equals(ForceUnit other)
        {
            return String.Equals(UnitName, other?.UnitName);
        }

        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            return obj is ForceUnit tmp && Equals(tmp);
        }

        public override int GetHashCode()
        {
            return UnitName?.GetHashCode() ?? 0;
        }

        /// <summary>
        /// Returns unit name
        /// </summary>
        public override string ToString()
        {
            return UnitName;
        }

        bool IEquatable<ForceUnit>.Equals(ForceUnit other)
        {
            return Equals(other);
        }

        /// <summary>
        /// Inequality operator
        /// </summary>
        /// <param name="left">first value to compare</param>
        /// <param name="right">second value to compare</param>
        public static bool operator !=(ForceUnit left, ForceUnit right)
        {
            return !left.Equals(right);
        }

        /// <summary>
        /// Equality operator
        /// </summary>
        /// <param name="left">first value to compare</param>
        /// <param name="right">second value to compare</param>
        public static bool operator ==(ForceUnit left, ForceUnit right)
        {
            return left.Equals(right);
        }

        /// <summary>
        /// Converts UnitDefinition&lt;ForceUnit&gt; into ForceUnit implicitly.
        /// </summary>
        /// <param name="src"></param>
        public static implicit operator ForceUnit(UnitDefinition<ForceUnit> src)
        {
            return src.Unit;
        }

        /// <summary>
        /// name of unit
        /// </summary>
        public string UnitName { get; }

    }

    [UnitsContainer]
    public static partial class ForceUnits
    {
        public static void RegisterUnitExchangeFactors(UnitExchangeFactors factors)
        {
            factors.RegisterMany(All);
        }

        public static ForceUnit TryRecoverUnitFromName([JetBrains.Annotations.NotNull] string unitName)
        {
            // generator : DerivedUnitGenerator.Add_TryRecoverUnitFromName
            if (unitName is null)
                throw new NullReferenceException(nameof(unitName));
            unitName = unitName.Trim();
            if (unitName.Length == 0)
                throw new ArgumentException(nameof(unitName));
            foreach (var i in All)
            {
                if (unitName == i.UnitName)
                    return i.Unit;
            }
            return new ForceUnit(unitName);
        }

        /// <summary>
        /// All known force units
        /// </summary>
        public static IReadOnlyList<UnitDefinition<ForceUnit>> All
        {
            get
            {
                return new []
                {
                    Newton,
                    KiloNewton,
                    MegaNewton,
                    MiliNewton
                };
            }
        }

        internal static readonly ForceUnit NewtonForceUnit = new ForceUnit("N");

        public static readonly UnitDefinition<ForceUnit> Newton = new UnitDefinition<ForceUnit>(NewtonForceUnit, 1m);

        internal static readonly ForceUnit KiloNewtonForceUnit = new ForceUnit("kN");

        public static readonly UnitDefinition<ForceUnit> KiloNewton = new UnitDefinition<ForceUnit>(KiloNewtonForceUnit, 1000m);

        internal static readonly ForceUnit MegaNewtonForceUnit = new ForceUnit("MN");

        public static readonly UnitDefinition<ForceUnit> MegaNewton = new UnitDefinition<ForceUnit>(MegaNewtonForceUnit, 1000000m);

        internal static readonly ForceUnit MiliNewtonForceUnit = new ForceUnit("mN");

        public static readonly UnitDefinition<ForceUnit> MiliNewton = new UnitDefinition<ForceUnit>(MiliNewtonForceUnit, 0.001m);

    }
}
