using System;
using System.Globalization;
using Newtonsoft.Json;

namespace iSukces.UnitedValues;

// -----===== autogenerated code =====-----
// ReSharper disable All
// generator: FractionValuesGenerator, UnitJsonConverterGenerator, MultiplyAlgebraGenerator, MultiplyAlgebraGenerator, MultiplyAlgebraGenerator, MultiplyAlgebraGenerator, MultiplyAlgebraGenerator, MultiplyAlgebraGenerator, MultiplyAlgebraGenerator, MultiplyAlgebraGenerator
[Serializable]
[JsonConverter(typeof(VolumeStreamJsonConverter))]
public partial struct VolumeStream : IUnitedValue<VolumeStreamUnit>, IEquatable<VolumeStream>, IFormattable
{
    /// <summary>
    /// creates instance of VolumeStream
    /// </summary>
    /// <param name="value">value</param>
    /// <param name="unit">unit</param>
    public VolumeStream(decimal value, VolumeStreamUnit unit)
    {
        Value = value;
        Unit = unit;
    }

    public VolumeStream(decimal value, VolumeUnit counterUnit, TimeUnit denominatorUnit)
    {
        Value = value;
        Unit = new VolumeStreamUnit(counterUnit, denominatorUnit);
    }

    public VolumeStream ConvertTo(VolumeStreamUnit newUnit)
    {
        // generator : FractionValuesGenerator.Add_ConvertTo
        if (Unit.Equals(newUnit))
            return this;
        var a = new Volume(Value, Unit.CounterUnit);
        var b = new Time(1, Unit.DenominatorUnit);
        a = a.ConvertTo(newUnit.CounterUnit);
        b = b.ConvertTo(newUnit.DenominatorUnit);
        return new VolumeStream(a.Value / b.Value, newUnit);
    }

    public bool Equals(VolumeStream other)
    {
        // generator : FractionValuesGenerator
        return Value == other.Value && Unit is not null && Unit.Equals(other.Unit);
    }

    public bool Equals(IUnitedValue<VolumeStreamUnit>? other)
    {
        // generator : FractionValuesGenerator
        if (other is null)
            return false;
        return Value == other.Value && Unit is not null && Unit.Equals(other.Unit);
    }

    public override bool Equals(object? other)
    {
        // generator : FractionValuesGenerator
        return other is IUnitedValue<VolumeStreamUnit> value && Equals(value);
    }

    public decimal GetBaseUnitValue()
    {
        // generator : BasicUnitValuesGenerator.Add_GetBaseUnitValue
        var factor1 = GlobalUnitRegistry.Factors.Get(Unit.CounterUnit);
        var factor2 = GlobalUnitRegistry.Factors.Get(Unit.DenominatorUnit);
        if ((factor1.HasValue && factor2.HasValue))
            return Value * factor1.Value / factor2.Value;
        throw new Exception("Unable to find multiplication for unit " + Unit);
    }

    public override int GetHashCode()
    {
        unchecked
        {
            return (Value.GetHashCode() * 397) ^ Unit.GetHashCode();
        }
    }

    public VolumeStream Round(int decimalPlaces)
    {
        return new VolumeStream(Math.Round(Value, decimalPlaces), Unit);
    }

    /// <summary>
    /// Returns unit name
    /// </summary>
    public override string ToString()
    {
        return Value.ToString(CultureInfo.InvariantCulture) + Unit.UnitName;
    }

    /// <summary>
    /// Returns unit name
    /// </summary>
    /// <param name="format"></param>
    /// <param name="provider"></param>
    public string ToString(string format, IFormatProvider provider = null)
    {
        return this.ToStringFormat(format, provider);
    }

    public VolumeStream WithCounterUnit(VolumeUnit newUnit)
    {
        // generator : FractionValuesGenerator.Add_WithCounterUnit
        var oldUnit = Unit.CounterUnit;
        if (oldUnit == newUnit)
            return this;
        var oldFactor = GlobalUnitRegistry.Factors.GetThrow(oldUnit);
        var newFactor = GlobalUnitRegistry.Factors.GetThrow(newUnit);
        var resultUnit = Unit.WithCounterUnit(newUnit);
        return new VolumeStream(oldFactor / newFactor * Value, resultUnit);
    }

    public VolumeStream WithDenominatorUnit(TimeUnit newUnit)
    {
        // generator : FractionValuesGenerator.Add_WithDenominatorUnit
        var oldUnit = Unit.DenominatorUnit;
        if (oldUnit == newUnit)
            return this;
        var oldFactor = GlobalUnitRegistry.Factors.GetThrow(oldUnit);
        var newFactor = GlobalUnitRegistry.Factors.GetThrow(newUnit);
        var resultUnit = Unit.WithDenominatorUnit(newUnit);
        return new VolumeStream(newFactor / oldFactor * Value, resultUnit);
    }

    /// <summary>
    /// Inequality operator
    /// </summary>
    /// <param name="left">first value to compare</param>
    /// <param name="right">second value to compare</param>
    public static bool operator !=(VolumeStream left, VolumeStream right)
    {
        return !left.Equals(right);
    }

    /// <summary>
    /// Division operation, calculates value dividend/divisor with unit that derives from dividend unit
    /// </summary>
    /// <param name="volumeStream">a dividend (counter) - a value that is being divided</param>
    /// <param name="area">a divisor (denominator) - a value which dividend is divided by</param>
    public static Velocity operator /(VolumeStream volumeStream, Area area)
    {
        // generator : MultiplyAlgebraGenerator.CreateCodeForLeftFractionValue
        // Velocity operator /(VolumeStream volumeStream, Area area)
        // scenario with hint
        // .Is<VolumeStream, Area, Velocity>("/")
        // hint location GetBasicOperatorHints, line 31
        var volumeStreamUnit = volumeStream.Unit;
        var tmp1 = volumeStreamUnit.CounterUnit;
        var resultUnit = new VelocityUnit(tmp1.GetLengthUnit(), volumeStreamUnit.DenominatorUnit);
        var areaConverted = area.ConvertTo(tmp1.GetAreaUnit());
        var value = volumeStream.Value / areaConverted.Value;
        return new Velocity(value, resultUnit);
    }

    /// <summary>
    /// Division operation, calculates value dividend/divisor with unit that derives from dividend unit
    /// </summary>
    /// <param name="volumeStream">a dividend (counter) - a value that is being divided</param>
    /// <param name="velocity">a divisor (denominator) - a value which dividend is divided by</param>
    public static Area operator /(VolumeStream volumeStream, Velocity velocity)
    {
        // generator : MultiplyAlgebraGenerator.CreateOperator
        // scenario with hint
        // .Is<VolumeStream, Velocity, Area>("/")
        // hint location GetBasicOperatorHints, line 31
        var volumeStreamUnit = volumeStream.Unit;
        var tmp1 = volumeStreamUnit.CounterUnit;
        var targetRightUnit = new VelocityUnit(tmp1.GetLengthUnit(), volumeStreamUnit.DenominatorUnit);
        var velocityConverted = velocity.ConvertTo(targetRightUnit);
        var value = volumeStream.Value / velocityConverted.Value;
        return new Area(value, tmp1.GetAreaUnit());
        // scenario F1
    }

    /// <summary>
    /// Division operation, calculates value dividend/divisor with unit that derives from dividend unit
    /// </summary>
    /// <param name="volumeStream">a dividend (counter) - a value that is being divided</param>
    /// <param name="area">a divisor (denominator) - a value which dividend is divided by</param>
    public static Velocity? operator /(VolumeStream? volumeStream, Area area)
    {
        // generator : MultiplyAlgebraGenerator.CreateCode
        if (volumeStream is null)
            return null;
        return volumeStream.Value / area;
    }

    /// <summary>
    /// Division operation, calculates value dividend/divisor with unit that derives from dividend unit
    /// </summary>
    /// <param name="volumeStream">a dividend (counter) - a value that is being divided</param>
    /// <param name="velocity">a divisor (denominator) - a value which dividend is divided by</param>
    public static Area? operator /(VolumeStream? volumeStream, Velocity velocity)
    {
        // generator : MultiplyAlgebraGenerator.CreateCode
        if (volumeStream is null)
            return null;
        return volumeStream.Value / velocity;
    }

    /// <summary>
    /// Division operation, calculates value dividend/divisor with unit that derives from dividend unit
    /// </summary>
    /// <param name="volumeStream">a dividend (counter) - a value that is being divided</param>
    /// <param name="area">a divisor (denominator) - a value which dividend is divided by</param>
    public static Velocity? operator /(VolumeStream volumeStream, Area? area)
    {
        // generator : MultiplyAlgebraGenerator.CreateCode
        if (area is null)
            return null;
        return volumeStream / area.Value;
    }

    /// <summary>
    /// Division operation, calculates value dividend/divisor with unit that derives from dividend unit
    /// </summary>
    /// <param name="volumeStream">a dividend (counter) - a value that is being divided</param>
    /// <param name="velocity">a divisor (denominator) - a value which dividend is divided by</param>
    public static Area? operator /(VolumeStream volumeStream, Velocity? velocity)
    {
        // generator : MultiplyAlgebraGenerator.CreateCode
        if (velocity is null)
            return null;
        return volumeStream / velocity.Value;
    }

    /// <summary>
    /// Division operation, calculates value dividend/divisor with unit that derives from dividend unit
    /// </summary>
    /// <param name="volumeStream">a dividend (counter) - a value that is being divided</param>
    /// <param name="area">a divisor (denominator) - a value which dividend is divided by</param>
    public static Velocity? operator /(VolumeStream? volumeStream, Area? area)
    {
        // generator : MultiplyAlgebraGenerator.CreateCode
        if (volumeStream is null || area is null)
            return null;
        return volumeStream.Value / area.Value;
    }

    /// <summary>
    /// Division operation, calculates value dividend/divisor with unit that derives from dividend unit
    /// </summary>
    /// <param name="volumeStream">a dividend (counter) - a value that is being divided</param>
    /// <param name="velocity">a divisor (denominator) - a value which dividend is divided by</param>
    public static Area? operator /(VolumeStream? volumeStream, Velocity? velocity)
    {
        // generator : MultiplyAlgebraGenerator.CreateCode
        if (volumeStream is null || velocity is null)
            return null;
        return volumeStream.Value / velocity.Value;
    }

    /// <summary>
    /// Equality operator
    /// </summary>
    /// <param name="left">first value to compare</param>
    /// <param name="right">second value to compare</param>
    public static bool operator ==(VolumeStream left, VolumeStream right)
    {
        return left.Equals(right);
    }

    public static VolumeStream Parse(string value)
    {
        // generator : FractionValuesGenerator.Add_Parse
        if (string.IsNullOrEmpty(value))
            throw new ArgumentNullException(nameof(value));
        var r = CommonParse.Parse(value, typeof(VolumeStream));
        var units = Common.SplitUnitNameBySlash(r.UnitName);
        if (units.Length != 2)
            throw new Exception($"{r.UnitName} is not valid VolumeStream unit");
        var counterUnit = new VolumeUnit(units[0]);
        var denominatorUnit = new TimeUnit(units[1]);
        return new VolumeStream(r.Value, counterUnit, denominatorUnit);
    }

    /// <summary>
    /// value
    /// </summary>
    public decimal Value { get; }

    /// <summary>
    /// unit
    /// </summary>
    public VolumeStreamUnit Unit { get; }

}

public partial class VolumeStreamJsonConverter : JsonConverter
{
    public override bool CanConvert(Type objectType)
    {
        return objectType == typeof(VolumeStreamUnit);
    }

    /// <summary>
    /// Reads the JSON representation of the object.
    /// </summary>
    /// <param name="reader">The JsonReader to read from.</param>
    /// <param name="objectType">Type of the object.</param>
    /// <param name="existingValue">The existing value of object being read.</param>
    /// <param name="serializer">The calling serializer.</param>
    public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
    {
        if (reader.ValueType == typeof(string))
        {
            if (objectType == typeof(VolumeStream))
                return VolumeStream.Parse((string)reader.Value);
        }
        throw new NotImplementedException();
    }

    public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
    {
        if (value is null)
            writer.WriteNull();
        else
            writer.WriteValue(value.ToString());
    }

}
